version: "3.0"
services:
  test:
    image: "python:${PYTHON_VERSION:-3.9}"
    volumes:
      - ./:/work
      - ./.pip_cache/${PYTHON_VERSION:-3.9}:/root/.cache/pip
    working_dir: /work
    network_mode: host
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Run tests with pytest"
        printf "Python: "; python --version
        pip install -r ./requirements-dev.txt

        python ./setup.py install
        flake8 src tests
        pytest tests --cov=src --cov-report=xml --cov-report=term --cov-report=html
